version: '2.1'
services:
  dbserver:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:      
      - MYSQL_ROOT_PASSWORD=root1pass
      - MYSQL_DATABASE=laravel_api
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - dbserver
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
  laravel:
    build: . 
    image: laravel_api
    container_name: laravel_api   
    volumes:
       - ./src:/var/www           
    depends_on:
       dbserver:
        condition: service_healthy
    links:
      - dbserver    
    ports:
      - '8080:80'  
    